"""
DeepDRAC — Centralized path and device configuration.

All paths are defined relative to the project root directory.
Set the environment variable `DEEPDRAC_ROOT` to override the project root,
otherwise it is auto-detected from this file's location.
"""

import os
from pathlib import Path

import torch

# Project root: the directory containing this config file
PROJECT_ROOT = Path(os.environ.get("DEEPDRAC_ROOT", Path(__file__).resolve().parent))

# ── Device ───────────────────────────────────────────────────────────────────
# Auto-detect GPU. Set CUDA_VISIBLE_DEVICES="" to force CPU.
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"DeepDRAC device: {DEVICE}")

# ── Data paths ──────────────────────────────────────────────────────────────
DATA_DIR = PROJECT_ROOT / "data"

# Alert logs (CIC-IDS2017 formatted CSV files from Snort)
ALERT_DIR = DATA_DIR / "alert_logs"
ALERT_CORRECTED_DIR = ALERT_DIR / "correct_data"

# Frequent pattern mining rules
FREQUENT_MINING_DIR = DATA_DIR / "frequent_mining"
FREQUENT_RULES_FILE = FREQUENT_MINING_DIR / "frequent_combinations_output.txt"

# Knowledge encodings (port-service, signature mappings)
KNOWLEDGE_DIR = DATA_DIR / "knowledge"

# Graph-format data (generated by data_process pipeline, consumed by training)
GRAPH_DATA_DIR = DATA_DIR / "graph_data"
PRE_TRAIN_DIR = GRAPH_DATA_DIR / "pre-train"

# ── Checkpoint paths ────────────────────────────────────────────────────────
CHECKPOINT_DIR = PROJECT_ROOT / "checkpoints"
PRE_TRAIN_MODEL_DIR = CHECKPOINT_DIR / "pre-train-model"
FINE_TUNE_MODEL_DIR = CHECKPOINT_DIR / "fine-tune-model3"  # default version

# ── Output paths ────────────────────────────────────────────────────────────
EVALUATION_DIR = PROJECT_ROOT / "src" / "evaluation"
EMBEDDING_DIR = EVALUATION_DIR / "graph_embeding_data"


def ensure_dirs():
    """Create essential directories if they don't exist."""
    for d in [DATA_DIR, ALERT_DIR, ALERT_CORRECTED_DIR, FREQUENT_MINING_DIR,
              KNOWLEDGE_DIR, GRAPH_DATA_DIR, PRE_TRAIN_DIR,
              CHECKPOINT_DIR, PRE_TRAIN_MODEL_DIR, FINE_TUNE_MODEL_DIR]:
        d.mkdir(parents=True, exist_ok=True)


if __name__ == "__main__":
    print(f"Project root: {PROJECT_ROOT}")
    print(f"Data dir:     {DATA_DIR}")
    print(f"Checkpoints:  {CHECKPOINT_DIR}")
    ensure_dirs()
    print("All directories verified.")
